name: next-js-docker-build-deployment 

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/terraform/**'

jobs:
  build:
    name: Next.js app docker build and deployment
    runs-on: ubuntu-latest

# Initialization
    steps:
      - name: Setup AWSCLI
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          arch: amd64   
        
      - name: SCM Checkout 
        uses: actions/checkout@v3

# Build docker image
      - name: Get Image Tag
        run: |
          echo "BUILD_NUMBER=$(echo ${{ github.run_number }})" >> $GITHUB_ENV

# Run docker image vulnerability scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_OFFLINE_SCAN: true
        with:
          image-ref: 'viswadocker96/nextjs-hello-world:2'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

  deploy-stage:
    name: deploy to stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to stage
        run: echo deploying
  deploy-prod:
    name: deploy to prod
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: trstringer,acdunnigan
      - name: Deploy to production
        run: echo deploying

